name: Run C++ Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++

    - name: Compile and Run C++ Code
      run: |
        g++ -o main.out -std=c++11 -Wall -Wextra -Werror "Problem 1 Greedy Algorithm.cpp"
        ./main.out
